import './globals.scss'
import { Inter } from 'next/font/google'
import Image from 'next/image'
//-----------images----------------------
import backUp from './res/backUp.png'
import backUpFull from './res/backUpFull.png'
import back from './res/back.jpg'
//---------------------------------------


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Alexey Romanovich',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Image src={back} className='back'/>
        <Image src={backUp}  className='imgUpLeft'/>
        <Image src={backUp}  className='imgUpRight'/>
        <Image src={backUpFull} className='imgUpFull'/> 
        
        {children}
      </body>
    </html>
  )
}
