import './globals.scss'
import { Inter } from 'next/font/google'
import Image from 'next/image'

//------------pages----------------------
import Main from './pages/main'
import AboutMe from './pages/aboutMe'
//---------------------------------------
//-----------images----------------------
import backUp from './res/backUp.png'
import backUpFull from './res/backUpFull.png'
//---------------------------------------


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Alexey Romanovich',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Image src={backUp}  className='imgUpLeft'/>
        <Image src={backUp}  className='imgUpRight'/>
        <Image src={backUpFull} className='imgUpFull'/>
        {/*--------------- pages ---------------------*/}
        <Main/>
        <AboutMe/>
        {/*-------------------------------------------*/}
      </body>
    </html>
  )
}
